#!/bin/bash
echo "starting tunnel for use with hubspot-cti-host ..."
echo ""
echo "hubspot-cti-host"
echo "make sure to copy the tunnel URL into the .env file under apps/hubspot-cti-host directory"
echo "with the key VITE_HUBSPOT_CTI_HOST_ORIGIN before running the hubspot-cti-host vite dev server using:"
echo "yarn workspace hubspot-cti-host dev or building a production run via: yarn workspace hubspot-cti-host build."
echo ""
echo "NOTE: you will also need to PATCH your Hubspot calling app with the new URL for it to load correctly."
echo ""
echo "hubspot-cti-plugin"
echo "make sure to copy the tunnel URL into the appConfig.js config file under the apps/hubspot-cti-plugin/public directory"
echo "at the object path: flex_hubspot_cti.HUBSPOT_CTI_HOST_ORIGIN beofre running workspace hubspot-cti-plugin start to start the local dev server."
echo "for production use the real origin must be added to Flex's config at this location. If it is not there the plugin will not load and will log an error."
echo ""
cloudflared tunnel --url http://localhost:5173